### ISSUE TITLE
STDOUT error

### ISSUE THREAD

**Issue by bnomei** [bnomei/kirby3-janitor#100]
@samzzi
https://forum.getkirby.com/t/kirby3-janitor-a-panel-button-to-run-jobs-defined-in-php/23573/14?u=bnomei

I also have the STDOUT problem with my first implementation of the new janitor.
Not to test I created a fully new and empty plainkit project and followed your readme for the example command and even there I get the STDOUT :thinking: Kirby CLI is installed btw…

As a work arround I tried working with the callbacks but as soon as I add a button to my page I always get an error when adding a new page.

Example button:

```yml
processRegistrations:
  type: janitor
  icon: cog
  progress: 'Processing...'
  command: 'janitor:job --key processRegistrations'
  label: Process registrations
```

So when I add that and I want to create a new page I receive this:

When I remove the button everything works as expected :thinking:

**Comment by bnomei** [comment]
![bca6f8b5679c9b0277240a7583562501abf9f461](https://user-images.githubusercontent.com/3265642/215448470-903e0974-3430-4dad-9a13-09da14de6195.jpeg)

**Comment by bnomei** [comment]
there are various things that can go wrong here. please zip and send me the plainkit.

**Comment by samzzi** [comment]
For the STDOUT problem (Plainkit Kirby, example code from README implemented): https://gnx.cloud/mykirby-commands-stdout-bug-oS5pMi/mykirby-commands-stdout-bug.zip

Fot the "page already exists" I'm having a hard time simulating that in a plainkit 🤔 Which would make wonder it's not a janitor problem but when I comment the janitor button I can add pages. If I uncomment the button I can't add pages. Either way it seems I'll have to do more testing and research on that one.

**Comment by bnomei** [comment]
the example is using an uninitallized `$model` where `$page` should be used. i will fix that.

**Comment by bnomei** [comment]
TIP: just call `kirby example` (name of your job) to better debug jobs in an actual terminal.

**Comment by lukehatfield** [comment]
I'm also getting this with my janitor call...
![image](https://user-images.githubusercontent.com/5399943/217067939-7d2ec603-7d43-40b8-9969-80ff229d0ea4.png)

**Comment by bnomei** [comment]
@jklue have you most recent CLI, kirby and janitor version?

there is an open issue which kirby will fix eventually but i need to verify an PR
https://github.com/bnomei/kirby3-janitor/pull/101
maybe its related. please tell me. a bit more about your setup

**Comment by bnomei** [comment]
the STDOUT error will appear as well if ANY exception is triggered by your code. nothing i can do there. please try with an command that executes not code at all.

**Comment by jklue** [comment]
Thanks @bnomei. I'm on...
Kirby v3.9.1
CLI v1.0.0
Janitor v3.4.2

I have the blueprints/site.yml blueprint as this...
```
title: Site

sections:
  pages:
    type: pages
  mainfields:
    type: fields
    fields:
      call_my_command:
        type: janitor
        #command: 'example --data test'
        command: 'janitor:job --key example --data test'
        label: Call `Example` Command
```
and the config/config.php as this
```<?php

return [
    'example' => function ($model, $data = null) {
        return [
            'status' => 200,
            'message' => $model->title() . ' ' . $data,
        ];
    },
    // ... other options
];
```

here's my test repo: https://github.com/visualdialogue/janitortest/
