### ISSUE TITLE
Support multilanguage Panels

### ISSUE THREAD

**Issue by ersoma** [bnomei/kirby3-janitor#112]
Hi,

I'm just wondering if it's planned to support multilanguage panels with this plugin in the future.
I tried inserting placeholder strings (https://getkirby.com/docs/cookbook/i18n/using-variables-in-language-strings) for the label or progress properties, but they are not translated.

Thanks!

**Comment by bnomei** [comment]
hi @ersoma somehow i did not notice your issue earlier. sorry about that. thats a good idea and i will add it asap.

**Comment by bnomei** [comment]
as far as i can tell that should already been working :D

https://github.com/bnomei/kirby3-janitor/blob/87ed4d8b4e734206c871d92cd08990cd3efc2b78/index.php#L113

what exactly did you try? can you post your blueprint?

**Comment by grommasdietz** [comment]
Using a label translation like:

```yml
createJobs:
  type: janitor
  command: 'janitor:render'
  label:
    en: Create thumbnails jobs
    de: Thumbnail-Jobs erstellen
```    

ends up in the error message: `Invalid value for „label“ in file: /…/htdocs/kirby/src/Toolkit/Component.php line: 165` (Tested with Janitor 4.0.1)

Or am I doing it wrong?
