### ISSUE TITLE
Cleaning cache : Janitor has no data from command

### ISSUE THREAD

**Issue by theamnesic** [bnomei/kirby3-janitor#119]
Hi!

From the documentation, `If you want you can also call any of [the core shipping with the CLI](https://github.com/getkirby/cli#available-core-commands) like clear:cache`, but the cache is not cleaned with those Blueprints : 

```
clean:
  type: janitor
  label: Clean cache
  progress: Cleaning cache...
  command: 'kirby clear:cache'
  success: "Cache empty"
  icon: trash
```
or 

```
clean:
  type: janitor
  label: Clean cache
  progress: Cleaning cache...
  command: 'clear:cache'
  success: "Cache empty"
  icon: trash
```

The green button return `Janitor has no data from command "kirby"` or `Janitor has no data from command "clear:cache"`

Thanks!
