### ISSUE TITLE
Render a single page

### ISSUE THREAD

**Issue by grommasdietz** [bnomei/kirby3-janitor#120]
Hi Bruno

I’m trying to create the thumbnail jobs for a current page via `janitor:render`. From my understanding it should just render the current page by default, when using it in the page blueprint like:

```yml
createJobs:
  type: janitor
  command: 'janitor:render'
  label: Create thumbnails jobs
  ```

Currently this triggers the rendering of all pages. It’s a little confusing since I expect to only render all pages when using --site flag like in the thumbs job. Is this an intended behavior? Is there a way in general to explicitly render only the current page?

(Edit: And a small side note, there seems to be an issue with the success message on buttons: `{{ count }} Seiten gerendert`)
