### ISSUE TITLE
Example for combining jobs with args

### ISSUE THREAD

**Issue by grommasdietz** [bnomei/kirby3-janitor#122]
Hello again

hopefully not disturbing and maybe helpful for others as well: Is there a way to combine jobs with passing args?
For example, `commands/thumbnails.php`:

```php
<?php

use Bnomei\Janitor;
use Kirby\CLI\CLI;

return [
    'description' => 'Render and create thumbnails',
    'args' => [] + Janitor::ARGS, // page, file, user, site, data, model
    'command' => static function ($cli): void {
        $pageId = $cli->arg('page');
        $page = page($pageId);

        janitor()->command('janitor:render --quiet');
        janitor()->command('janitor:thumbs --quiet');

        janitor()->data($cli->arg('command'), [
            'status' => 200,
            'message' => 'Rendered pages and generated thumbs successfully for page: ' . $page->title(),
        ]);
    }
];
```

And referencing in blueprint like:
```yaml
thumbnails:
  type: janitor
  command: 'thumbnails' # commands/thumbnails
  label:
    en: Create thumbnails
    de: Thumbnails erstellen
```

Is working fine, but when trying to only render and create thumbnails for current page, it seems not to work at all:
```php
        janitor()->command('janitor:render --query page --quiet');
        janitor()->command('janitor:thumbs --quiet'); // do we need to pass '--page page' in this case?
```

I’m thankful for any hints.

**Comment by grommasdietz** [comment]
Got it working, maybe I messed it up somewhere else. Sorry! For anyone running into similar problems, inside `commands/thumbnails.php`:

```php
<?php

use Bnomei\Janitor;
use Kirby\CLI\CLI;

return [
    'description' => 'Render and create thumbnails',
    'args' => [] + Janitor::ARGS, // page, file, user, site, data, model
    'command' => static function ($cli): void {
        janitor()->command('janitor:render --quiet --query' .  $cli->arg('page'));
        janitor()->command('janitor:thumbs --quiet --page');

        janitor()->data($cli->arg('command'), [
            'status' => 200,
        ]);
    }
];
```

And in the blueprint, e.g. `blueprints/tabs/files.yml`:

```yaml
      janitor:
        type: fields
        width: 1/2
        fields:
          thumbnails:
            type: janitor
            command: thumbnails
            label:
              en: Create thumbnails
              de: Thumbnails erstellen
            progress:
              en: Creating thumbnails
              de: Erstelle Thumbnails
            success:
              en: Thumbnails created
              de: Thumbnails erstellt
            error:
              en: Creation failed
              de: Erstellung fehlgeschlagen
```
