### ISSUE TITLE
Generate thumbs from existing thumb jobs error

### ISSUE THREAD

**Issue by theamnesic** [bnomei/kirby3-janitor#126]
Hi!

This [example](https://github.com/bnomei/kirby3-janitor?tab=readme-ov-file#examples) seems not working anymore:

```
janitor_thumbssite:
  type: janitor
  command: 'janitor:thumbs --site'
  label: Generate thumbs from existing thumb jobs (full site)
```

I've got this error: 

`array_shift(): Argument #1 ($array) must be of type array, null given`

Kirby 4.3.0
Janitor 4.2.0

Thanks!
