### ISSUE TITLE
Button placement with width:1/2

### ISSUE THREAD

**Issue by movingwater** [bnomei/kirby3-janitor#132]
Is there a way to place the button at the same height as the input fields if the field is used in conjunction with `width: 1/2` or something like that?
It's just a cosmetic issue, but it would still be nice

![Image](https://github.com/user-attachments/assets/66e40147-2d0d-49b2-bca8-8cec080b4ebb)

**Comment by bnomei** [comment]
```yml
      jansite:
        type: janitor
        command: 'janitor:clipboard --data "{< site.title >}"'
        label: 'Clip'
        headline: " "   #<------ use headline like this (since 5.2.0)
        help: 'Copy'
        width: 1/2
```
