### ISSUE TITLE
Fail to load ressource (panel level>2)

### ISSUE THREAD

**Issue by Yoh7** [bnomei/kirby3-janitor#17]
**Describe the bug** : janitor works on level 1 or 2 but failed to load ressource deeper
![jani1](https://user-images.githubusercontent.com/40626038/68274702-21185e80-006a-11ea-8e27-c724190bf594.jpg)

**To Reproduce**
1. fesh starterkit
2. unzip master.zip as folder site/plugins/kirby3-janitor
3. modify site/blueprints/album.yml : add at the end : 
```
  janitor:
    type: janitor
    label: Clean Cache
    progress: Cleaning...
    job: clean
```
4. visit panel & click on "Clean cache"

**Kirby Version**
    3.3
    Fresh starterkit

**Desktop** (please complete the following information):
    Win7
    Browser: Firefox, Chrome
