### ISSUE TITLE
Feature: Disable button as long as page not saved

### ISSUE THREAD

**Issue by andreasotto** [bnomei/kirby3-janitor#33]
I'd like to request a feature: It should be possible to have the button disabled as long as the page is in dirty state and is not saved.

I have the situation where users click a janitor button, which depends on data from page - but the page had not been saved yet, so the janitor button doesn't use the new data. Things are going wrong then. Therefore i think it wold be an advantage if the button could be configured to be disabled as long as the page is in not-saved state.

**Comment by bnomei** [comment]
see wiki...
https://github.com/bnomei/kirby3-janitor/wiki/Panel-Field-Option:-Unsaved-Changes

```yml
  janitor:
    type: janitor
    label: Clean Cache
    progress: Cleaning Cache...
    job: cleanCache
    unsaved: false            # <--------
```
