### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by nncrns** [bnomei/kirby3-janitor#34]
Hello there, thank you for this plugin. I would like to use it to provide backup functionality via the Panel. However, the backup is not generated correctly. Any pointers on what is going wrong here?

I have saved and unzipped the repo in site/plugins as `kirby3-janitor`.

In my blueprint:
```
sections:
     backup:
          type: fields
          fields:
               janitor:
                    type: janitor
                    label: Download backup
                    progress: Creating backup...
                    job: backupZip
```
This is the error I am getting once I click the "Download Backup" button:

<img width="967" alt="Bildschirmfoto 2020-10-09 um 11 46 37" src="https://user-images.githubusercontent.com/47850358/95569146-7781e000-0a25-11eb-9b04-2ad20633268c.png">
