### ISSUE TITLE
Enhancement suggestion: be able to query data property for user

### ISSUE THREAD

**Issue by vauvarin** [bnomei/kirby3-janitor#46]
In the current version of janitor, the data property only works for page and file models. It could be nice to be able to query data property for user too.

My use case: I need a janitor button in a user blueprint to trigger a user field update. For this, I need to get the user id in the Janitor jobs by the data property to update the right fields.

**/blueprints/users/journalist.yml**
```
journalistUpdate:
  type: janitor
  label: Confirm this update
  job: updateJournalistValidated
  data: '{{ user.id }}'
```
**config.php**
```
'updateJournalistValidated' => function (Kirby\Cms\Page $page = null, string $data = null ) {
            $kirby = kirby();
            $kirby->impersonate();
            $journalist = $kirby->user( $data );
            if ( !empty( $journalist ) ) :
                $journalist->update([
                    'journalistState'  => '',
                    'updateJournalistValidatedInfo' => '',
                ]);
            endif;
            return [
                'status'    => 200,
                'reload'    => true,
            ];
        },
```
