### ISSUE TITLE
custom janitor button on site.yml

### ISSUE THREAD

**Issue by bvdputte** [bnomei/kirby3-janitor#52]
Is it expected that my custom janitor job button doesn't work from `site.yml` blueprint without adding a `data` (which I don't need) property to it?

This is my `site.yml`:

```yaml
janitor:
  type: janitor
  label: Replenish my custom cache
  progress: Replenishing (can take a few secs)...
  cooldown: 5000
  job: replenishMyCache
  data: blablabla
```
and this is the job defined in my `config.php`:
```php
'bnomei.janitor.jobs' => [
    'replenishMyCache' => function (Kirby\Cms\Page $page = null, string $data = null) {
        var_dump($page);
        var_dump($data);
        die;
        return [
            'status' => 200,
            'label' => 'External stuff fetched',
        ];
    },
]
```

When I remove `data: blablabla` from the blueprint, the button doesn't work and I get a 404 in the panel for the call: `http://mywebsite.test/api/plugin-janitor/replenishMyCache/$` -> I notice a `$` is appended? Is this expected?
FYI: when `data: blablabla` is in the blueprint, the url that is fetched looks like this: `http://mywebsite.test/api/plugin-janitor/replenishMyCache/%24/mlkqsjdf`

Am I doing something wrong?

----

When I test this on a page blueprint, I don't need to add the `data` property. It just works as expected then?
