### ISSUE TITLE
Translateable labels for janitor fields

### ISSUE THREAD

**Issue by tobimori** [bnomei/kirby3-janitor#98]
Janitor field doesn't support multi-lang labels in blueprints.

### Blueprint
```yaml
              downloadContent:
                label:
                  de: Content herunterladen (.zip)
                  en: Download content (.zip)
                type: janitor
                command: 'download-content'
```

### Error:
<img width="393" alt="CleanShot 2022-12-18 at 17 02 54@2x" src="https://user-images.githubusercontent.com/29142128/208307819-72b3dcb2-8048-49c2-854c-e9607b731e8a.png">

### Expected behavior
Button text would be "Content herunterladen (.zip)" if logged in with a German account, but "Download content (.zip)" if logged in with an English account.
